insilico_COLO829_100pc:
  manta_svpri: /g/data/gx8/projects/Hsu_WGS_Validation/colo829-merged/final/insilico_COLO829_100pc/COLO829_100pc-sv-prioritize-manta.vcf.gz
  ensemble: /g/data/gx8/projects/Hsu_WGS_Validation/colo829-merged/final/2018-08-18_colo829-merged/COLO829_100pc-ensemble-annotated.vcf.gz
insilico_COLO829_20pc:
  manta_svpri: /g/data/gx8/projects/Hsu_WGS_Validation/colo829-merged/final/insilico_COLO829_20pc/COLO829_20pc-sv-prioritize-manta.vcf.gz
  ensemble: /g/data/gx8/projects/Hsu_WGS_Validation/colo829-merged/final/2018-08-18_colo829-merged/COLO829_20pc-ensemble-annotated.vcf.gz
insilico_COLO829_40pc:
  manta_svpri: /g/data/gx8/projects/Hsu_WGS_Validation/colo829-merged/final/insilico_COLO829_40pc/COLO829_40pc-sv-prioritize-manta.vcf.gz
  ensemble: /g/data/gx8/projects/Hsu_WGS_Validation/colo829-merged/final/2018-08-18_colo829-merged/COLO829_40pc-ensemble-annotated.vcf.gz
insilico_COLO829_60pc:
  manta_svpri: /g/data/gx8/projects/Hsu_WGS_Validation/colo829-merged/final/insilico_COLO829_60pc/COLO829_60pc-sv-prioritize-manta.vcf.gz
  ensemble: /g/data/gx8/projects/Hsu_WGS_Validation/colo829-merged/final/2018-08-18_colo829-merged/COLO829_60pc-ensemble-annotated.vcf.gz
insilico_COLO829_80pc:
  manta_svpri: /g/data/gx8/projects/Hsu_WGS_Validation/colo829-merged/final/insilico_COLO829_80pc/COLO829_80pc-sv-prioritize-manta.vcf.gz
  ensemble: /g/data/gx8/projects/Hsu_WGS_Validation/colo829-merged/final/2018-08-18_colo829-merged/COLO829_80pc-ensemble-annotated.vcf.gz

