insilico_COLO829_100pc:
  insilico_COLO829_100pc:
    bam: /g/data/gx8/projects/Hsu_WGS_Validation/colo829-merged/final/insilico_COLO829_100pc/insilico_COLO829_100pc-ready
    name: insilico_COLO829_100pc
    phenotype: tumor
  insilico_COLO829BL:
    bam: /g/data/gx8/projects/Hsu_WGS_Validation/colo829-merged/final/insilico_COLO829BL/insilico_COLO829BL-ready
    name: insilico_COLO829BL
    phenotype: normal
insilico_COLO829_20pc:
  insilico_COLO829_20pc:
    bam: /g/data/gx8/projects/Hsu_WGS_Validation/colo829-merged/final/insilico_COLO829_20pc/insilico_COLO829_20pc-ready
    name: insilico_COLO829_20pc
    phenotype: tumor
  insilico_COLO829BL:
    bam: /g/data/gx8/projects/Hsu_WGS_Validation/colo829-merged/final/insilico_COLO829BL/insilico_COLO829BL-ready
    name: insilico_COLO829BL
    phenotype: normal
insilico_COLO829_40pc:
  insilico_COLO829_40pc:
    bam: /g/data/gx8/projects/Hsu_WGS_Validation/colo829-merged/final/insilico_COLO829_40pc/insilico_COLO829_40pc-ready
    name: insilico_COLO829_40pc
    phenotype: tumor
  insilico_COLO829BL:
    bam: /g/data/gx8/projects/Hsu_WGS_Validation/colo829-merged/final/insilico_COLO829BL/insilico_COLO829BL-ready
    name: insilico_COLO829BL
    phenotype: normal
insilico_COLO829_60pc:
  insilico_COLO829_60pc:
    bam: /g/data/gx8/projects/Hsu_WGS_Validation/colo829-merged/final/insilico_COLO829_60pc/insilico_COLO829_60pc-ready
    name: insilico_COLO829_60pc
    phenotype: tumor
  insilico_COLO829BL:
    bam: /g/data/gx8/projects/Hsu_WGS_Validation/colo829-merged/final/insilico_COLO829BL/insilico_COLO829BL-ready
    name: insilico_COLO829BL
    phenotype: normal
insilico_COLO829_80pc:
  insilico_COLO829_80pc:
    bam: /g/data/gx8/projects/Hsu_WGS_Validation/colo829-merged/final/insilico_COLO829_80pc/insilico_COLO829_80pc-ready
    name: insilico_COLO829_80pc
    phenotype: tumor
  insilico_COLO829BL:
    bam: /g/data/gx8/projects/Hsu_WGS_Validation/colo829-merged/final/insilico_COLO829BL/insilico_COLO829BL-ready
    name: insilico_COLO829BL
    phenotype: normal

