batch1:
  normal:
    bam: /path/to/bam1
    alias: sample1_N
  tumor:
    bam: /path/to/bam2
    alias: sample1_T
batch2:
  normal:
    bam: /path/to/bam3
    alias: sample2_N
  tumor:
    bam: /path/to/bam4
    alias: sample2_T

