batch1:
  HCC2218_T:
    bam: /data/cephfs/punim0010/projects/Diakumis_HCC2218/bcbio/final/HCC2218C/HCC2218C-ready
    name: HCC2218_T
    phenotype: tumor
  HCC2218_N:
    bam: /data/cephfs/punim0010/projects/Diakumis_HCC2218/bcbio/final/HCC2218BL/HCC2218BL-ready
    name: HCC2218_N
    phenotype: normal

