error_diff_ids.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/error_diff_ids.fastq
  fname: error_diff_ids.fastq
error_double_qual.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/error_double_qual.fastq
  fname: error_double_qual.fastq
error_double_seq.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/error_double_seq.fastq
  fname: error_double_seq.fastq
error_long_qual.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/error_long_qual.fastq
  fname: error_long_qual.fastq
error_no_qual.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/error_no_qual.fastq
  fname: error_no_qual.fastq
error_qual_del.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/error_qual_del.fastq
  fname: error_qual_del.fastq
error_qual_escape.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/error_qual_escape.fastq
  fname: error_qual_escape.fastq
error_qual_null.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/error_qual_null.fastq
  fname: error_qual_null.fastq
error_qual_space.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/error_qual_space.fastq
  fname: error_qual_space.fastq
error_qual_tab.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/error_qual_tab.fastq
  fname: error_qual_tab.fastq
error_qual_unit_sep.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/error_qual_unit_sep.fastq
  fname: error_qual_unit_sep.fastq
error_qual_vtab.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/error_qual_vtab.fastq
  fname: error_qual_vtab.fastq
error_short_qual.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/error_short_qual.fastq
  fname: error_short_qual.fastq
error_spaces.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/error_spaces.fastq
  fname: error_spaces.fastq
error_tabs.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/error_tabs.fastq
  fname: error_tabs.fastq
error_trunc_at_plus.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/error_trunc_at_plus.fastq
  fname: error_trunc_at_plus.fastq
error_trunc_at_qual.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/error_trunc_at_qual.fastq
  fname: error_trunc_at_qual.fastq
error_trunc_at_seq.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/error_trunc_at_seq.fastq
  fname: error_trunc_at_seq.fastq
error_trunc_in_plus.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/error_trunc_in_plus.fastq
  fname: error_trunc_in_plus.fastq
error_trunc_in_qual.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/error_trunc_in_qual.fastq
  fname: error_trunc_in_qual.fastq
error_trunc_in_seq.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/error_trunc_in_seq.fastq
  fname: error_trunc_in_seq.fastq
error_trunc_in_title.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/error_trunc_in_title.fastq
  fname: error_trunc_in_title.fastq
illumina_full_range_as_illumina.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/illumina_full_range_as_illumina.fastq
  fname: illumina_full_range_as_illumina.fastq
illumina_full_range_as_sanger.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/illumina_full_range_as_sanger.fastq
  fname: illumina_full_range_as_sanger.fastq
illumina_full_range_as_solexa.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/illumina_full_range_as_solexa.fastq
  fname: illumina_full_range_as_solexa.fastq
illumina_full_range_original_illumina.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/illumina_full_range_original_illumina.fastq
  fname: illumina_full_range_original_illumina.fastq
longreads_as_illumina.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/longreads_as_illumina.fastq
  fname: longreads_as_illumina.fastq
longreads_as_sanger.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/longreads_as_sanger.fastq
  fname: longreads_as_sanger.fastq
longreads_as_solexa.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/longreads_as_solexa.fastq
  fname: longreads_as_solexa.fastq
longreads_original_sanger.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/longreads_original_sanger.fastq
  fname: longreads_original_sanger.fastq
misc_dna_as_illumina.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/misc_dna_as_illumina.fastq
  fname: misc_dna_as_illumina.fastq
misc_dna_as_sanger.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/misc_dna_as_sanger.fastq
  fname: misc_dna_as_sanger.fastq
misc_dna_as_solexa.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/misc_dna_as_solexa.fastq
  fname: misc_dna_as_solexa.fastq
misc_dna_original_sanger.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/misc_dna_original_sanger.fastq
  fname: misc_dna_original_sanger.fastq
misc_rna_as_illumina.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/misc_rna_as_illumina.fastq
  fname: misc_rna_as_illumina.fastq
misc_rna_as_sanger.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/misc_rna_as_sanger.fastq
  fname: misc_rna_as_sanger.fastq
misc_rna_as_solexa.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/misc_rna_as_solexa.fastq
  fname: misc_rna_as_solexa.fastq
misc_rna_original_sanger.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/misc_rna_original_sanger.fastq
  fname: misc_rna_original_sanger.fastq
sanger_full_range_as_illumina.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/sanger_full_range_as_illumina.fastq
  fname: sanger_full_range_as_illumina.fastq
sanger_full_range_as_sanger.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/sanger_full_range_as_sanger.fastq
  fname: sanger_full_range_as_sanger.fastq
sanger_full_range_as_solexa.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/sanger_full_range_as_solexa.fastq
  fname: sanger_full_range_as_solexa.fastq
sanger_full_range_original_sanger.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/sanger_full_range_original_sanger.fastq
  fname: sanger_full_range_original_sanger.fastq
solexa_full_range_as_illumina.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/solexa_full_range_as_illumina.fastq
  fname: solexa_full_range_as_illumina.fastq
solexa_full_range_as_sanger.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/solexa_full_range_as_sanger.fastq
  fname: solexa_full_range_as_sanger.fastq
solexa_full_range_as_solexa.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/solexa_full_range_as_solexa.fastq
  fname: solexa_full_range_as_solexa.fastq
solexa_full_range_original_solexa.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/solexa_full_range_original_solexa.fastq
  fname: solexa_full_range_original_solexa.fastq
wrapping_as_illumina.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/wrapping_as_illumina.fastq
  fname: wrapping_as_illumina.fastq
wrapping_as_sanger.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/wrapping_as_sanger.fastq
  fname: wrapping_as_sanger.fastq
wrapping_as_solexa.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/wrapping_as_solexa.fastq
  fname: wrapping_as_solexa.fastq
wrapping_original_sanger.fastq:
  abspath: /Users/pdiakumis/Downloads/fastq_invalid_tests/wrapping_original_sanger.fastq
  fname: wrapping_original_sanger.fastq

