AWSTemplateFormatVersion: 2010-09-09
Description: >-
  (WWPS-GLS-WF-BATCH) Deploys resource for a AWS Batch environment that is
  suitable for genomics, including a default JobQueue.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "AWS Batch Environment Config"
        Parameters:
          - LaunchTemplateId
          - VpcId
          - SubnetIds
          - SpotBidPercentage
          - DefaultCEMinvCpus
          - DefaultCEMaxvCpus
          - BatchServiceRoleArn
          - Ec2InstanceProfileArn
          - SpotFleetRoleArn
    ParameterLabels:
      LaunchTemplateId:
        default: Launch Template ID
      VpcId:
        default: VPC ID
      SubnetIds:
        default: VPC Subnet IDs
      SpotBidPercentage:
        default: Spot market bid percentage (default = 100)
      DefaultCEMinvCpus:
        default: Default Queue Min vCPU count
      DefaultCEMaxvCpus:
        default: Default Queue Max vCPU count
      BatchServiceRoleArn:
        default: AWS Batch service role ARN
      Ec2InstanceProfileArn:
        default: EC2 Instance Profile ARN
      SpotFleetRoleArn:
        default: Spot Fleet Role ARN

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "The VPC to create security groups and deploy AWS Batch to. NOTE: Must be the same VPC as the provided subnet IDs."
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: "Subnets you want your batch compute environment to launch in. We recommend private subnets. NOTE: Must be from the VPC provided."
  SpotBidPercentage:
    Type: Number
    Description: Maximum Spot bid percentage from on-demand instance price.
    MaxValue: 100
    MinValue: 5
    Default: 100
  LaunchTemplateId:
    Type: String
    Description: Launch Template you want your AWS Batch Compute Environments to use
  DefaultCEMinvCpus:
    Type: Number
    Description: Minimum number of CPUs in the default compute environment. Default 0.
    Default: 0
    MinValue: 0
  DefaultCEMaxvCpus:
    Type: Number
    Description: Maximum number of CPUs in the default compute environment. Should be >= than MinCpus
    Default: 100
    MinValue: 0
  BatchServiceRoleArn:
    Type: String
    Description: The IAM Role ARN for the Batch service
  SpotFleetRoleArn:
    Type: String
    Description: The IAM Role ARN for Batch to call Spot Fleet service
  Ec2InstanceProfileArn:
    Type: String
    Description: The IAM Role ARN for the Batch service

Resources:
  GenomicsBatchSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG for genomics workflows on Batch
      VpcId:
        Ref: VpcId
  SGSSHIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref GenomicsBatchSecurityGroup
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      CidrIp: 0.0.0.0/0
  SGAllTcpEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref GenomicsBatchSecurityGroup
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      CidrIp: 0.0.0.0/0
  SGAllTcpSelfIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref GenomicsBatchSecurityGroup
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      SourceSecurityGroupId: !Ref GenomicsBatchSecurityGroup

  GenomicsDefaultComputeEnv:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      ComputeEnvironmentName: !Sub
        - spot-${StackGuid}
        - StackGuid: !Select [2, !Split ["/", !Ref "AWS::StackId"]]
      ServiceRole: !Ref BatchServiceRoleArn
      Type: MANAGED
      State: ENABLED
      ComputeResources:
        BidPercentage: !Ref SpotBidPercentage
        # Ec2KeyPair: !Ref Ec2KeyPairName
        LaunchTemplate:
          LaunchTemplateId: !Ref LaunchTemplateId
        InstanceRole: !Ref Ec2InstanceProfileArn
        InstanceTypes:
          - optimal
        MinvCpus: !Ref DefaultCEMinvCpus
        MaxvCpus: !Ref DefaultCEMaxvCpus
        SecurityGroupIds:
          - !Ref GenomicsBatchSecurityGroup
        SpotIamFleetRole: !Ref SpotFleetRoleArn
        Subnets: !Ref SubnetIds
        Type: SPOT
        Tags:
          Name: !Sub
            - batch-spot-worker-${StackGuid}
            - StackGuid: !Select [2, !Split ["/", !Ref "AWS::StackId"]]

  GenomicsDefaultQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: !Sub
        - default-${StackGuid}
        - StackGuid: !Select [2, !Split ["/", !Ref "AWS::StackId"]]
      Priority: 1
      State: ENABLED
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref GenomicsDefaultComputeEnv

Outputs:
  DefaultJobQueueArn:
    Value: !Ref GenomicsDefaultQueue
