channels:
  - pdiakumis
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools
  - click>=7.0
  - jinja2            # for snakemake report
  - ldc=1.11.0        # for sambamba
  - networkx          # for snakemake report
  - pygraphviz        # for snakemake report
  - python>=3.6
  - snakemake
  - sambamba
  - samtools
  - r-base
  - r-tidyverse
  - r-devtools
  - r-dt
  - r-optparse
  - r-knitr
  - r-rmarkdown
  - r-bookdown
