name: woof

channels:
  - pdiakumis
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - bcftools
  - click
  - cromwell
  - fqtools
  - pandoc
  - python>=3.6
  - samtools
  - r-base>=3.5
  - r-devtools
  - r-dt
  - r-radix
  - r-knitr
  - r-rmarkdown
  - r-tidyverse
